### ISSUE TITLE
Script Error Upon running /installer.sh

### ISSUE THREAD

**Issue by cyclone018** [JustTemmie/steam-presence#27]
Trying to get this to work on my arch linux system. Any idea?

Testing if the script works

----------------------------------------------------------
[Aug 23 2023 - 09:51:25] progam's current folder structure version is up to date...
----------------------------------------------------------
[Aug 23 2023 - 09:51:25] loading config file
Traceback (most recent call last):
  File "/home/phantom/steam-presence/./main.py", line 1058, in <module>
    main()
  File "/home/phantom/steam-presence/./main.py", line 869, in main
    config = getConfigFile()
             ^^^^^^^^^^^^^^^
  File "/home/phantom/steam-presence/./main.py", line 138, in getConfigFile
    userSettings = json.load(f)
                   ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 5 column 6 (char 141)

Here is my config file:
![image](https://github.com/JustTemmie/steam-presence/assets/71578464/9eda2735-5f62-40fb-8adf-436a91eeec44)

**Comment by cyclone018** [comment]
Fixed:
Used a Kwrite instead of kate. Extremely weird on how the json file was saved and wouldn't open in any other application.
