### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by v-127** [JustTemmie/steam-presence#65]
I get connection refused when it tries to create a new rich presence object

`[nekkles@NekklesOS steam-presence]$ python3 main.py
----------------------------------------------------------
[Jul 17 2024 - 14:28:38] progam's current folder structure version is up to date...
----------------------------------------------------------
[Jul 17 2024 - 14:28:38] loading config file
[Jul 17 2024 - 14:28:38] intializing the SteamGrid database...
[Jul 17 2024 - 14:28:38] everything is ready!
----------------------------------------------------------
[Jul 17 2024 - 14:28:38] found game THE FINALS played by Nekkles
[Jul 17 2024 - 14:28:40] steam app ID 2073850 found for THE FINALS
[Jul 17 2024 - 14:28:41] game changed, updating to 'THE FINALS'
[Jul 17 2024 - 14:28:41] fetching the Discord game ID for THE FINALS
[Jul 17 2024 - 14:28:42] found the discord game ID for the finals
[Jul 17 2024 - 14:28:42] fetching icon for THE FINALS
[Jul 17 2024 - 14:28:42] found icon for THE FINALS in cache
[Jul 17 2024 - 14:28:42] creating new rich presence object for THE FINALS
Traceback (most recent call last):
  File "/home/nekkles/steam-presence/main.py", line 1201, in <module>
    main()
  File "/home/nekkles/steam-presence/main.py", line 1182, in main
    RPC.connect()
  File "/home/nekkles/.local/lib/python3.12/site-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nekkles/.local/lib/python3.12/site-packages/pypresence/baseclient.py", line 112, in handshake
    self.sock_reader, self.sock_writer = await asyncio.wait_for(asyncio.open_unix_connection(ipc_path), self.connection_timeout)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 261, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 659, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
`

**Comment by connerdavis47** [comment]
Same here. Maybe a Python change caused this? Worked for me for several weeks until about a week ago, and I have had Arch distribute a few Python upgrades in that time, I think.

```
Jul 25 15:27:00 baine python[1887016]:     await self.sock_connect(sock, path)
Jul 25 15:27:00 baine python[1887016]:   File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
Jul 25 15:27:00 baine python[1887016]:     return await fut
Jul 25 15:27:00 baine python[1887016]:            ^^^^^^^^^
Jul 25 15:27:00 baine python[1887016]:   File "/usr/lib/python3.12/asyncio/selector_events.py", line 659, in _sock_connect
Jul 25 15:27:00 baine python[1887016]:     sock.connect(address)
```

**Comment by JustTemmie** [comment]
i believe that your virtual environment breaks when your OS's python version got updated, you should be able to fix it by just deleting it and remaking it 

`rm -rf venv/`
`python3 -m venv venv/`
`./venv/bin/python -m pip install -r requirements.txt`

**Comment by connerdavis47** [comment]
> i believe that your virtual environment breaks when your OS's python version got updated, you should be able to fix it by just deleting it and remaking it
> 
> `rm -rf venv/` `python3 -m venv venv/` `./venv/bin/python -m pip install -r requirements.txt`

Thanks for the reply! TBH, this didn't work for me initially but I've since restarted my computer and it just... kinda... works now? Not sure. I had also tried to reinstall before your suggestion which I think includes the step you suggested. Not sure what actually changed but I will take it :)

**Comment by JustTemmie** [comment]
seems fixed
